### ISSUE TITLE
Invalid value for event_id: not a valid string.

### ISSUE THREAD

**Issue by giedriusStan** [stape-io/tiktok-tag#10]
With PlaceAnOrder event, we receive the following response:

{"code":40002,"message":"Invalid value for event_id: not a valid string.","request_id":"202303141300390EF6F5D96D1798201C51"}

![2023-03-14_15-07](https://user-images.githubusercontent.com/1705190/225010783-542b970e-49c9-4719-b70d-544d4b15b6ba.png)

**Comment by Bukashk0zzz** [comment]
You use for event_id "273196"
TikTok required to use xxxxx_xxxxx format for event_id https://ads.tiktok.com/marketing_api/docs?id=1741601162187777

You can override event_id using tag settings.

<img width="840" alt="Screenshot 2023-03-19 at 18 21 08" src="https://user-images.githubusercontent.com/1908342/226194916-12c3d520-ba25-453d-b47e-c94990b522ae.png">
