### ISSUE TITLE
Switch mapping of purchase-events to use CompletePayment

### ISSUE THREAD

**Issue by SimenHansen** [stape-io/tiktok-tag#21]
Suggestion to move the mapping of purchase events from `PlaceAnOrder` to `CompletePayment`

This comes after feedback from my local TikTok-rep on the Ads-side.
For correct optimization rules for the out-of-the-box bidding within TikTok a purchase-event should be tracked as `CompletePayment`.
The distinction being that `PlaceAnOrder` is meant for an order where you come back later to do the payment. More of a "soft"-conversion. 

See also the definitions from [TikTok Events](https://ads.tiktok.com/help/article/supported-standard-events)

> Place an Order | When a visitor places an order. TikTok recommends using this event when placing an order and making a payment are not the same.

Versus

> Complete Payment |  When a visitor makes a payment. TikTok recommends using this event when placing an order and making a payment are the same.

**Comment by Bukashk0zzz** [comment]
@SimenHansen Thanks for the issue.
It is now fixed.
