### ISSUE TITLE
Make "Logs Settings" option defaulted to log debug & preview

### ISSUE THREAD

**Issue by alexgarciab** [stape-io/tiktok-tag#25]
The current default option in the "Logs Settings" section is "Do not log".

Can you please make the default option the one by the name "Log to console during debug and preview"?

This is how the rest of the Tags are configured. Not sure why TikTok tag is configured in a different way.

**Comment by Bukashk0zzz** [comment]
@kHorozhanov Can you please check this.

**Comment by Bukashk0zzz** [comment]
Hi,

Issue fixed.
