### ISSUE TITLE
Missing some important "User Parameters"

### ISSUE THREAD

**Issue by alexgarciab** [stape-io/tiktok-tag#26]
I miss some important "User Parameters" in this template such as:

- first_name
- last_name
- city
- state
- country
- zip_code

Documentation: https://business-api.tiktok.com/gateway/docs/index?identify_key=c0138ffadd90a955c1f0670a56fe348d1d40680b3c89461e09f78ed26785164b&language=ENGLISH&doc_id=1771101151059969

Can you please add them?

**Comment by Bukashk0zzz** [comment]
That's already implemented

**Comment by alexgarciab** [comment]
@Bukashk0zzz where is it implemented? I don't see it.

![tikok-user-data](https://github.com/stape-io/tiktok-tag/assets/6924386/097e4b47-2706-42b2-b853-cb3311b69ce9)

**Comment by Bukashk0zzz** [comment]
Hi,

Feature added.

**Comment by alexgarciab** [comment]
@Bukashk0zzz this seems to be working, however, I am not sure if these additional parameters should show up in the "Customer Information Parameters" section of the "Test Events" view in TikTok Events. Currently they are not showing, but I am still getting a good response body:

`{"code": 0, "message": "OK", "request_id": "20240705092320323C2F514AF49BCF4621", "data": {}}`

![user-data-array](https://github.com/stape-io/tiktok-tag/assets/6924386/12290f59-899f-4cd7-9835-c4ee4414e2cf)

![tiktok-activity](https://github.com/stape-io/tiktok-tag/assets/6924386/12869f06-d8d8-4f67-a3e6-a8916bb35bcb)

**Comment by mrsnippy** [comment]
@alexgarciab we assume that's a lack of UI update on TikTok side, I've tested with new user parameters and I see the same behaviour although everything is passed according to the documentation and we do get a 200 response
