### ISSUE TITLE
`test_event_code` cannot be dynamically set via GTM transformations

### ISSUE THREAD

**Issue by n4bb12** [stape-io/tiktok-tag#27]
These lines hard-replace the `test_event_code` with the value from the tag configuration, overriding a value on the source event or dynamically set by a GTM transformation:
https://github.com/stape-io/tiktok-tag/blob/21d023b4190f3f13931f5db66703dd96781f3076/template.js#L161-L163

This is better solved in the facebook-tag where existing event parameters take precedence, allowing `test_event_code` to be set dynamically:
https://github.com/stape-io/facebook-tag/blob/c3fbe0854fe803bc769d568a9a77e89bc7495d94/template.js#L73-L77

**Comment by Bukashk0zzz** [comment]
Hi,

Issue is fixed.
