### ISSUE TITLE
Content type mapping

### ISSUE THREAD

**Issue by bashoogzaad** [stape-io/tiktok-tag#4]
Hello,

When I test 'ViewContent' for example, the TikTok dashboard generates a warning that the 'content_type' is not set. I do not seem to get where I can set it. It would be possible to set this up with the datalayer, however there is not field from 'item' which I can use. (see https://developers.google.com/analytics/devguides/collection/ga4/reference/events#purchase_item)

So how should I set this field?

Kind regards!

**Comment by Bukashk0zzz** [comment]
You can create your own contents array and override it contents value
https://ads.tiktok.com/marketing_api/docs?id=1727541103358977
<img width="1020" alt="Screenshot 2022-04-04 at 18 18 55" src="https://user-images.githubusercontent.com/1908342/161576558-6c71f3b7-163b-4d59-aec8-aad5c1e64fb1.png">


Also you can send items array in ga4 format to server and it will be parsed 
https://github.com/stape-io/tiktok-tag/blob/master/template.js#L163
