### ISSUE TITLE
Upgrade to API v1.3

### ISSUE THREAD

**Issue by khanhicetea** [stape-io/tiktok-tag#5]
First, thank you for the good template :)

Btw, can we upgrade to new API version if you have some spare time :)

New version of API 1.3 : https://ads.tiktok.com/marketing_api/docs?id=1740579480076290

API call response warning header 

```
X-Api-Deprecation-Info: API for Business Version 1.3 is now live. To avoid disruption to your business, we recommend you migrate all calls to v1.3 as soon as possible. Please visit our migration guide for more details: https://ads.tiktok.com/marketing_api/docs?id=1740029169927169
```

Thank you!

**Comment by Bukashk0zzz** [comment]
Hi,

Thanks for the issue.
We already have plans to update the tag to support the new API version and add new functionality. We will make these changes by the end of the following week.

**Comment by Bukashk0zzz** [comment]
Template updated. https://github.com/stape-io/tiktok-tag/commit/33063104d3302c5722fde8bd0fec6cd797674467
