### ISSUE TITLE
Regarding cookie ttclid not being created

### ISSUE THREAD

**Issue by ahmedmaazin** [stape-io/tiktok-tag#6]
Thank you so much for the template. Appreciate this a lot :)

I'm having trouble getting conversion data from a running TikTok ad. Conversion stays 0. TikTok docs I saw that I need this param to be in the URL itself `&ttclid=__CLICKID__` & I missed adding it.

Question is, is it due to the `ttclid` not being available in the URL and I am redirecting the users from the TikTok app to the website the reason why the `ttclid` cookie is not getting created? or do you have an idea what might be wrong?

**Comment by Bukashk0zzz** [comment]
There can be a lot of issues why you don't see any conversion. 
ttclid in the URL is pretty important for conversion tracking.

> Question is, is it due to the ttclid not being available in the URL and I am redirecting the users from the TikTok app to the website the reason why the ttclid cookie is not getting created?

Correct. You need ttclid to create a TikTok clock cookie.

p.s. This question not relates the template itself.
